koi/urls.py
from django.urls import path

from . import admin_views, views

app_name = "koi"
urlpatterns = [
    # Public views
    path("", views.IndexView.as_view(), name="index"),
    path("<int:koinoxrista_id>/", views.DapanesViewDet, name="dapanes"),
    path("<int:koin_id>/dist", views.distribution, name="katanomi"),
    path("xiliosta/", views.xiliosta_view, name="xiliosta"),
    path("<int:apod_id>/apodeijeis/", views.apodeijeis, name="apodeijeis"),
    # Custom Admin Dashboard
    path("manage/", admin_views.admin_dashboard, name="admin_dashboard"),
    # Category Admin
    path("manage/categories/", admin_views.category_list, name="admin_category_list"),
    path(
        "manage/categories/create/",
        admin_views.category_create,
        name="admin_category_create",
    ),
    path(
        "manage/categories/<int:pk>/edit/",
        admin_views.category_edit,
        name="admin_category_edit",
    ),
    path(
        "manage/categories/<int:pk>/delete/",
        admin_views.category_delete,
        name="admin_category_delete",
    ),
    # Diamerisma Admin
    path(
        "manage/diamerismata/",
        admin_views.diamerisma_list,
        name="admin_diamerisma_list",
    ),
    path(
        "manage/diamerismata/create/",
        admin_views.diamerisma_create,
        name="admin_diamerisma_create",
    ),
    path(
        "manage/diamerismata/<int:pk>/edit/",
        admin_views.diamerisma_edit,
        name="admin_diamerisma_edit",
    ),
    path(
        "manage/diamerismata/<int:pk>/delete/",
        admin_views.diamerisma_delete,
        name="admin_diamerisma_delete",
    ),
    # Diaxeiristis Admin
    path(
        "manage/diaxeiristes/",
        admin_views.diaxeiristis_list,
        name="admin_diaxeiristis_list",
    ),
    path(
        "manage/diaxeiristes/create/",
        admin_views.diaxeiristis_create,
        name="admin_diaxeiristis_create",
    ),
    path(
        "manage/diaxeiristes/<int:pk>/edit/",
        admin_views.diaxeiristis_edit,
        name="admin_diaxeiristis_edit",
    ),
    path(
        "manage/diaxeiristes/<int:pk>/delete/",
        admin_views.diaxeiristis_delete,
        name="admin_diaxeiristis_delete",
    ),
    # Koinoxrista Admin
    path(
        "manage/koinoxrista/",
        admin_views.koinoxrista_list,
        name="admin_koinoxrista_list",
    ),
    path(
        "manage/koinoxrista/create/",
        admin_views.koinoxrista_create,
        name="admin_koinoxrista_create",
    ),
    path(
        "manage/koinoxrista/<int:pk>/edit/",
        admin_views.koinoxrista_edit,
        name="admin_koinoxrista_edit",
    ),
    path(
        "manage/koinoxrista/<int:pk>/delete/",
        admin_views.koinoxrista_delete,
        name="admin_koinoxrista_delete",
    ),
    # Xiliosta Admin
    path("manage/xiliosta/", admin_views.xiliosta_list, name="admin_xiliosta_list"),
    path(
        "manage/xiliosta/create/",
        admin_views.xiliosta_create,
        name="admin_xiliosta_create",
    ),
    path(
        "manage/xiliosta/<int:pk>/edit/",
        admin_views.xiliosta_edit,
        name="admin_xiliosta_edit",
    ),
    path(
        "manage/xiliosta/<int:pk>/delete/",
        admin_views.xiliosta_delete,
        name="admin_xiliosta_delete",
    ),
    # Dapanes Admin
    path("manage/dapanes/", admin_views.dapanes_list, name="admin_dapanes_list"),
    path(
        "manage/dapanes/create/",
        admin_views.dapanes_create,
        name="admin_dapanes_create",
    ),
    path(
        "manage/dapanes/<int:pk>/edit/",
        admin_views.dapanes_edit,
        name="admin_dapanes_edit",
    ),
    path(
        "manage/dapanes/<int:pk>/delete/",
        admin_views.dapanes_delete,
        name="admin_dapanes_delete",
    ),
]

main/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("koi.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

koi/forms.py
from django import forms

from .models import Category, Dapanes, Diamerisma, Diaxeiristis, Koinoxrista, Xiliosta


class TailwindFormMixin:
    """Mixin to add Tailwind CSS classes to form fields"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # Base classes for all inputs
            base_classes = (
                "block w-full rounded-lg border border-gray-300 bg-gray-50 "
                "p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 "
                "dark:border-gray-600 dark:bg-gray-700 dark:text-white "
                "dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            )

            if isinstance(field.widget, forms.Textarea):
                field.widget.attrs["class"] = base_classes + " min-h-[100px]"
                field.widget.attrs["rows"] = 4
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs["class"] = base_classes
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs["class"] = (
                    "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded "
                    "focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 "
                    "focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                )
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs["class"] = base_classes
                field.widget.attrs["type"] = "date"
            else:
                field.widget.attrs["class"] = base_classes

            # Add placeholder
            if field.label:
                field.widget.attrs["placeholder"] = field.label


class CategoryForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = ["category"]
        labels = {"category": "Κατηγορία"}


class DiamerismaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Diamerisma
        fields = ["name", "num", "orofos", "sizesm", "owner", "guest"]
        widgets = {
            "sizesm": forms.NumberInput(attrs={"step": "0.01"}),
        }


class DiaxeiristisForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Diaxeiristis
        fields = ["name", "date_from", "sex"]
        widgets = {
            "date_from": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk:
            self.fields["date_from"].widget.attrs["value"] = (
                self.instance.date_from.strftime("%Y-%m-%d")
                if self.instance.date_from
                else ""
            )


class KoinoxristaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Koinoxrista
        fields = ["ekdosi", "diaxeiristis", "sxolia", "url", "published"]
        widgets = {
            "ekdosi": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "sxolia": forms.Textarea(attrs={"rows": 4}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk:
            self.fields["ekdosi"].widget.attrs["value"] = (
                self.instance.ekdosi.strftime("%Y-%m-%d")
                if self.instance.ekdosi
                else ""
            )


class XiliostaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Xiliosta
        fields = ["diamerisma", "category", "xiliosta"]


class DapanesForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Dapanes
        fields = ["koinoxrista", "category", "par_date", "par_num", "par_per", "value"]
        widgets = {
            "par_date": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "value": forms.NumberInput(attrs={"step": "0.01"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk and self.instance.par_date:
            self.fields["par_date"].widget.attrs["value"] = (
                self.instance.par_date.strftime("%Y-%m-%d")
            )


# Inline formset for Dapanes within Koinoxrista
DapanesFormSet = forms.inlineformset_factory(
    Koinoxrista, Dapanes, form=DapanesForm, extra=1, can_delete=True
)

koi/views.py
"""Test"""
from collections import namedtuple

from django.db.models import Sum
from django.shortcuts import get_object_or_404, render
from django.views import generic

from utils.distribute import distribute_view
from utils.greek_utils import gr2float, grdate, grnum

from . import models as mdl


class IndexView(generic.ListView):
    template_name = "koi/index.html"
    context_object_name = "koinoxrista_list"

    def get_queryset(self):
        return mdl.Koinoxrista.objects.filter(published=True).order_by("-ekdosi")


class DapanesView(generic.DetailView):
    model = mdl.Koinoxrista
    template_name = "koi/dapanes.html"


def DapanesViewDet(request, koinoxrista_id):
    Gdat = namedtuple("Gdata", "value align")
    koin = get_object_or_404(mdl.Koinoxrista, pk=koinoxrista_id)
    categories = mdl.Category.objects.order_by("id")
    dapanes = koin.dapanes_set.all().order_by("par_date")
    ttot = {}
    gtotal = 0
    for cat in categories:
        ttot[cat.category] = 0.0
    tdi = []
    for dap in dapanes:
        ddi = {
            "t_date": Gdat(grdate(dap.par_date), "center"),
            "t_par": Gdat(dap.par_num, "center"),
            "t_per": Gdat(dap.par_per, "left"),
        }
        for cat in categories:
            ddi[cat.category] = ""
        ddi[dap.category.category] = Gdat(grnum(dap.value), "right")
        ttot[dap.category.category] += float(dap.value)
        gtotal += float(dap.value)
        tdi.append(ddi)
    gtotal = grnum(gtotal)
    ttot = {key: grnum(val) for key, val in ttot.items()}
    return render(
        request,
        "koi/dapanes.html",
        {
            "dapanes": tdi,
            "total": ttot,
            "koin": koin,
            "cats": categories,
            "gtotal": gtotal,
            "clen": len(categories),
        },
    )


def xiliosta_view(request):
    categories = mdl.Category.objects.order_by("id")
    xiliosta = mdl.Xiliosta.objects.order_by("diamerisma")
    tdi = {}
    ttot = {"name": "Σύνολα"}
    for cat in categories:
        ttot[cat.category] = 0
    for xil in xiliosta:
        dname = xil.diamerisma.guest
        ddi = {"name": dname}
        for cat in categories:
            ddi[cat.category] = 0
        tdi[dname] = tdi.get(dname, ddi)
        tdi[dname][xil.category.category] = xil.xiliosta
        ttot[xil.category.category] += xil.xiliosta
    return render(
        request,
        "koi/xiliosta.html",
        {"categories": categories, "xiliosta": tdi, "totals": ttot},
    )


def calc_distribution(koin_id):
    diamer = {i.id: i.guest for i in mdl.Diamerisma.objects.all().order_by("id")}
    categ = {i.id: i.category for i in mdl.Category.objects.all().order_by("id")}
    xiliosta = mdl.Xiliosta.objects.all()
    koin = mdl.Koinoxrista.objects.get(pk=koin_id)
    dap_per_cat = (
        koin.dapanes_set.values("category")
        .order_by("category")
        .annotate(tvalue=Sum("value"))
    )
    header, data, footer = distribute_view(dap_per_cat, xiliosta, diamer, categ)
    return header, data, footer, koin


def distribution(request, koin_id):
    header, data, footer, koin = calc_distribution(koin_id)
    title = f"Κατανομή κοινοχρήστων δαπανών {koin.id}-{grdate(koin.ekdosi)}"

    return render(
        request,
        "koi/katanomi.html",
        {
            "title": title,
            "headers": header,
            "lines": data,
            "footer1": footer,
        },
    )


def apodeijeis(request, apod_id):
    diamerismata = mdl.Diamerisma.objects.all().order_by("id")
    xiliosta = mdl.Xiliosta.objects.all()
    koin = mdl.Koinoxrista.objects.get(pk=apod_id)
    dap = koin.dapanes_set.values()
    cate = [i.id for i in mdl.Category.objects.all().order_by("id")]
    diam = [i.id for i in mdl.Diamerisma.objects.all().order_by("id")]
    fdi = {}
    # Καρτεσιανό γινόμενο διαμερίσματα Χ κατηγορίες με αρχική τιμή 0
    for c in cate:
        for d in diam:
            fdi[(c, d)] = 0
    # Αντικατάσταση με τιμές από τη βάση δεδομένων
    for el in xiliosta:
        fdi[(el.category.id, el.diamerisma.id)] = el.xiliosta
    adi = {
        "headers": ["Ημ/νία", "Παρ/κό", "Περιγραφή", "Ποσό", "Χιλιοστά", "Αναλογούν"]
    }
    adi["diamerismata"] = diamerismata
    adi["koinoxrista"] = koin
    adi["ptitle"] = "Απόδειξη εξώφλησης κοινοχρήστων"
    adi["lines"] = []
    _, data, _, _ = calc_distribution(apod_id)
    totals1 = [i[-1] for i in data]
    for i, diamerisma in enumerate(diamerismata):
        dline = {"diamerisma": diamerisma, "lines": [], "footer": []}
        total = 0
        for dapani in dap:
            xiliosta = fdi[(dapani["category_id"], diamerisma.id)]
            anal = round(xiliosta / 1000 * float(dapani["value"]), 2)
            total = round(total + anal, 2)
            line = [
                {"lcr": "center", "val": dapani["par_date"]},
                {"lcr": "center", "val": dapani["par_num"]},
                {"lcr": "left", "val": dapani["par_per"]},
                {"lcr": "right", "val": dapani["value"]},
                {"lcr": "center", "val": xiliosta},
                {"lcr": "right", "val": grnum(anal)},
            ]
            dline["lines"].append(line)

        dline["footer1"] = [
            {"span": 5, "lcr": "center", "val": "Πληρωτέο ποσό"},
            {"span": 1, "lcr": "right", "val": totals1[i]},
        ]
        if total != 0:
            if abs(total - gr2float(totals1[i])) > 0.05:
                raise ValueError
            adi["lines"].append(dline)

    return render(request, "koi/apodeijeis.html", adi)

koi/templates/koi/includes/footer.html
{% load static %}
<footer class="footer-color text-center footer-text no-print">
  <div class="container p-4">

      <div class="row d-flex">
        {% csrf_token %}

        <div class="col-auto">
          <button type="button" class="btn btn-outline-primary no-print" onclick="javascript:window.print()">Εκτύπωση</button>
          {% comment %} <button onclick="javascript:window.print()" class="no-print">Εκτύπωση</button> {% endcomment %}
        </div>

        <div class="col-auto">
          <p>© {% now "Y" %} Ted Lazaros</p>
        </div>
      </div>
</footer>

koi/templates/koi/includes/messaging.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

koi/templates/koi/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-color navbar-fixed-top">
  <div class="container">
    <!-- Navbar Left Side -->
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/">Home</a>
    </div>
    <button
      aria-controls="navbarToggle"
      aria-expanded="false"
      aria-label="Toggle navigation"
      class="navbar-toggler ml-auto float-right btncolor"
      data-target="#navbarToggle"
      data-toggle="collapse"
      type="button"
    >
      <i class="fas fa-bars fa-2x"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggle">
      <!-- Navbar Left Side -->
      <div class="navbar-nav mr-auto">
        <a class="nav-item nav-link" href="#">About</a>
      </div>
      <!-- Navbar Right Side -->
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'koi:xiliosta' %}">Χιλιοστά</a>
        {% if user.is_authenticated %} {% if user.is_superuser %}
        <a class="nav-item nav-link" href="#">New Post</a>
        <a class="nav-item nav-link" href="#">New Dataset</a>
        <a class="nav-item nav-link" href="#">Datasets</a>
        {% endif %}
        <a class="nav-item nav-link" href="#"> {{user.username}} <i class="fas fa-user"></i> </a>
        <a class="nav-item nav-link" href="#"> Log out <i class="fas fa-sign-out-alt"></i> </a>
        {% else %}
        <a class="nav-item nav-link" href="#"> Log in <i class="fas fa-sign-in-alt"></i> </a>
        <a class="nav-item nav-link" href="#"> Sign up <i class="fas fa-user-plus"></i> </a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

koi/templates/koi/includes/navbar1.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Αρχική</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'koi:xiliosta' %}">Χιλιοστά</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">---</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'koi:admin_dashboard' %}">manage</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Database</a>
      </li>
      <li class="nav-item">
        <form method="post" action="{% url 'logout' %}" class="d-inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-success my-2 my-sm-0">{{ user.username }} (logout)</button>
        </form>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'admin:index' %}">login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>