koi/urls.py
from django.urls import path

from . import admin_views, views

app_name = "koi"
urlpatterns = [
    # Public views
    path("", views.IndexView.as_view(), name="index"),
    path("<int:koinoxrista_id>/", views.DapanesViewDet, name="dapanes"),
    path("<int:koin_id>/dist", views.distribution, name="katanomi"),
    path("xiliosta/", views.xiliosta_view, name="xiliosta"),
    path("<int:apod_id>/apodeijeis/", views.apodeijeis, name="apodeijeis"),
    # Custom Admin Dashboard
    path("manage/", admin_views.admin_dashboard, name="admin_dashboard"),
    # Category Admin
    path("manage/categories/", admin_views.category_list, name="admin_category_list"),
    path(
        "manage/categories/create/",
        admin_views.category_create,
        name="admin_category_create",
    ),
    path(
        "manage/categories/<int:pk>/edit/",
        admin_views.category_edit,
        name="admin_category_edit",
    ),
    path(
        "manage/categories/<int:pk>/delete/",
        admin_views.category_delete,
        name="admin_category_delete",
    ),
    # Diamerisma Admin
    path(
        "manage/diamerismata/",
        admin_views.diamerisma_list,
        name="admin_diamerisma_list",
    ),
    path(
        "manage/diamerismata/create/",
        admin_views.diamerisma_create,
        name="admin_diamerisma_create",
    ),
    path(
        "manage/diamerismata/<int:pk>/edit/",
        admin_views.diamerisma_edit,
        name="admin_diamerisma_edit",
    ),
    path(
        "manage/diamerismata/<int:pk>/delete/",
        admin_views.diamerisma_delete,
        name="admin_diamerisma_delete",
    ),
    # Diaxeiristis Admin
    path(
        "manage/diaxeiristes/",
        admin_views.diaxeiristis_list,
        name="admin_diaxeiristis_list",
    ),
    path(
        "manage/diaxeiristes/create/",
        admin_views.diaxeiristis_create,
        name="admin_diaxeiristis_create",
    ),
    path(
        "manage/diaxeiristes/<int:pk>/edit/",
        admin_views.diaxeiristis_edit,
        name="admin_diaxeiristis_edit",
    ),
    path(
        "manage/diaxeiristes/<int:pk>/delete/",
        admin_views.diaxeiristis_delete,
        name="admin_diaxeiristis_delete",
    ),
    # Koinoxrista Admin
    path(
        "manage/koinoxrista/",
        admin_views.koinoxrista_list,
        name="admin_koinoxrista_list",
    ),
    path(
        "manage/koinoxrista/create/",
        admin_views.koinoxrista_create,
        name="admin_koinoxrista_create",
    ),
    path(
        "manage/koinoxrista/<int:pk>/edit/",
        admin_views.koinoxrista_edit,
        name="admin_koinoxrista_edit",
    ),
    path(
        "manage/koinoxrista/<int:pk>/delete/",
        admin_views.koinoxrista_delete,
        name="admin_koinoxrista_delete",
    ),
    # Xiliosta Admin
    path("manage/xiliosta/", admin_views.xiliosta_list, name="admin_xiliosta_list"),
    path(
        "manage/xiliosta/create/",
        admin_views.xiliosta_create,
        name="admin_xiliosta_create",
    ),
    path(
        "manage/xiliosta/<int:pk>/edit/",
        admin_views.xiliosta_edit,
        name="admin_xiliosta_edit",
    ),
    path(
        "manage/xiliosta/<int:pk>/delete/",
        admin_views.xiliosta_delete,
        name="admin_xiliosta_delete",
    ),
    # Dapanes Admin
    path("manage/dapanes/", admin_views.dapanes_list, name="admin_dapanes_list"),
    path(
        "manage/dapanes/create/",
        admin_views.dapanes_create,
        name="admin_dapanes_create",
    ),
    path(
        "manage/dapanes/<int:pk>/edit/",
        admin_views.dapanes_edit,
        name="admin_dapanes_edit",
    ),
    path(
        "manage/dapanes/<int:pk>/delete/",
        admin_views.dapanes_delete,
        name="admin_dapanes_delete",
    ),
]

main/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("koi.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

koi/forms.py
from django import forms

from .models import Category, Dapanes, Diamerisma, Diaxeiristis, Koinoxrista, Xiliosta


class TailwindFormMixin:
    """Mixin to add Tailwind CSS classes to form fields"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # Base classes for all inputs
            base_classes = (
                "block w-full rounded-lg border border-gray-300 bg-gray-50 "
                "p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 "
                "dark:border-gray-600 dark:bg-gray-700 dark:text-white "
                "dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            )

            if isinstance(field.widget, forms.Textarea):
                field.widget.attrs["class"] = base_classes + " min-h-[100px]"
                field.widget.attrs["rows"] = 4
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs["class"] = base_classes
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs["class"] = (
                    "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded "
                    "focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 "
                    "focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                )
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs["class"] = base_classes
                field.widget.attrs["type"] = "date"
            else:
                field.widget.attrs["class"] = base_classes

            # Add placeholder
            if field.label:
                field.widget.attrs["placeholder"] = field.label


class CategoryForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = ["category"]
        labels = {"category": "Κατηγορία"}


class DiamerismaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Diamerisma
        fields = ["name", "num", "orofos", "sizesm", "owner", "guest"]
        widgets = {
            "sizesm": forms.NumberInput(attrs={"step": "0.01"}),
        }


class DiaxeiristisForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Diaxeiristis
        fields = ["name", "date_from", "sex"]
        widgets = {
            "date_from": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk:
            self.fields["date_from"].widget.attrs["value"] = (
                self.instance.date_from.strftime("%Y-%m-%d")
                if self.instance.date_from
                else ""
            )


class KoinoxristaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Koinoxrista
        fields = ["ekdosi", "diaxeiristis", "sxolia", "url", "published"]
        widgets = {
            "ekdosi": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "sxolia": forms.Textarea(attrs={"rows": 4}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk:
            self.fields["ekdosi"].widget.attrs["value"] = (
                self.instance.ekdosi.strftime("%Y-%m-%d")
                if self.instance.ekdosi
                else ""
            )


class XiliostaForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Xiliosta
        fields = ["diamerisma", "category", "xiliosta"]


class DapanesForm(TailwindFormMixin, forms.ModelForm):
    class Meta:
        model = Dapanes
        fields = ["koinoxrista", "category", "par_date", "par_num", "par_per", "value"]
        widgets = {
            "par_date": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
            "value": forms.NumberInput(attrs={"step": "0.01"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure date field uses the correct format for HTML5 date input
        if self.instance and self.instance.pk and self.instance.par_date:
            self.fields["par_date"].widget.attrs["value"] = (
                self.instance.par_date.strftime("%Y-%m-%d")
            )


# Inline formset for Dapanes within Koinoxrista
DapanesFormSet = forms.inlineformset_factory(
    Koinoxrista, Dapanes, form=DapanesForm, extra=1, can_delete=True
)

koi/views.py
"""Test"""
from collections import namedtuple

from django.db.models import Sum
from django.shortcuts import get_object_or_404, render
from django.views import generic

from utils.distribute import distribute_view
from utils.greek_utils import gr2float, grdate, grnum

from . import models as mdl


class IndexView(generic.ListView):
    template_name = "koi/index.html"
    context_object_name = "koinoxrista_list"

    def get_queryset(self):
        return mdl.Koinoxrista.objects.filter(published=True).order_by("-ekdosi")


class DapanesView(generic.DetailView):
    model = mdl.Koinoxrista
    template_name = "koi/dapanes.html"


def DapanesViewDet(request, koinoxrista_id):
    Gdat = namedtuple("Gdata", "value align")
    koin = get_object_or_404(mdl.Koinoxrista, pk=koinoxrista_id)
    categories = mdl.Category.objects.order_by("id")
    dapanes = koin.dapanes_set.all().order_by("par_date")
    ttot = {}
    gtotal = 0
    for cat in categories:
        ttot[cat.category] = 0.0
    tdi = []
    for dap in dapanes:
        ddi = {
            "t_date": Gdat(grdate(dap.par_date), "center"),
            "t_par": Gdat(dap.par_num, "center"),
            "t_per": Gdat(dap.par_per, "left"),
        }
        for cat in categories:
            ddi[cat.category] = ""
        ddi[dap.category.category] = Gdat(grnum(dap.value), "right")
        ttot[dap.category.category] += float(dap.value)
        gtotal += float(dap.value)
        tdi.append(ddi)
    gtotal = grnum(gtotal)
    ttot = {key: grnum(val) for key, val in ttot.items()}
    return render(
        request,
        "koi/dapanes.html",
        {
            "dapanes": tdi,
            "total": ttot,
            "koin": koin,
            "cats": categories,
            "gtotal": gtotal,
            "clen": len(categories),
        },
    )


def xiliosta_view(request):
    categories = mdl.Category.objects.order_by("id")
    xiliosta = mdl.Xiliosta.objects.order_by("diamerisma")
    tdi = {}
    ttot = {"name": "Σύνολα"}
    for cat in categories:
        ttot[cat.category] = 0
    for xil in xiliosta:
        dname = xil.diamerisma.guest
        ddi = {"name": dname}
        for cat in categories:
            ddi[cat.category] = 0
        tdi[dname] = tdi.get(dname, ddi)
        tdi[dname][xil.category.category] = xil.xiliosta
        ttot[xil.category.category] += xil.xiliosta
    return render(
        request,
        "koi/xiliosta.html",
        {"categories": categories, "xiliosta": tdi, "totals": ttot},
    )


def calc_distribution(koin_id):
    diamer = {i.id: i.guest for i in mdl.Diamerisma.objects.all().order_by("id")}
    categ = {i.id: i.category for i in mdl.Category.objects.all().order_by("id")}
    xiliosta = mdl.Xiliosta.objects.all()
    koin = mdl.Koinoxrista.objects.get(pk=koin_id)
    dap_per_cat = (
        koin.dapanes_set.values("category")
        .order_by("category")
        .annotate(tvalue=Sum("value"))
    )
    header, data, footer = distribute_view(dap_per_cat, xiliosta, diamer, categ)
    return header, data, footer, koin


def distribution(request, koin_id):
    header, data, footer, koin = calc_distribution(koin_id)
    title = f"Κατανομή κοινοχρήστων δαπανών {koin.id}-{grdate(koin.ekdosi)}"

    return render(
        request,
        "koi/katanomi.html",
        {
            "title": title,
            "headers": header,
            "lines": data,
            "footer1": footer,
        },
    )


def apodeijeis(request, apod_id):
    diamerismata = mdl.Diamerisma.objects.all().order_by("id")
    xiliosta = mdl.Xiliosta.objects.all()
    koin = mdl.Koinoxrista.objects.get(pk=apod_id)
    dap = koin.dapanes_set.values()
    cate = [i.id for i in mdl.Category.objects.all().order_by("id")]
    diam = [i.id for i in mdl.Diamerisma.objects.all().order_by("id")]
    fdi = {}
    # Καρτεσιανό γινόμενο διαμερίσματα Χ κατηγορίες με αρχική τιμή 0
    for c in cate:
        for d in diam:
            fdi[(c, d)] = 0
    # Αντικατάσταση με τιμές από τη βάση δεδομένων
    for el in xiliosta:
        fdi[(el.category.id, el.diamerisma.id)] = el.xiliosta
    adi = {
        "headers": ["Ημ/νία", "Παρ/κό", "Περιγραφή", "Ποσό", "Χιλιοστά", "Αναλογούν"]
    }
    adi["diamerismata"] = diamerismata
    adi["koinoxrista"] = koin
    adi["ptitle"] = "Απόδειξη εξώφλησης κοινοχρήστων"
    adi["lines"] = []
    _, data, _, _ = calc_distribution(apod_id)
    totals1 = [i[-1] for i in data]
    for i, diamerisma in enumerate(diamerismata):
        dline = {"diamerisma": diamerisma, "lines": [], "footer": []}
        total = 0
        for dapani in dap:
            xiliosta = fdi[(dapani["category_id"], diamerisma.id)]
            anal = round(xiliosta / 1000 * float(dapani["value"]), 2)
            total = round(total + anal, 2)
            line = [
                {"lcr": "center", "val": dapani["par_date"]},
                {"lcr": "center", "val": dapani["par_num"]},
                {"lcr": "left", "val": dapani["par_per"]},
                {"lcr": "right", "val": dapani["value"]},
                {"lcr": "center", "val": xiliosta},
                {"lcr": "right", "val": grnum(anal)},
            ]
            dline["lines"].append(line)

        dline["footer1"] = [
            {"span": 5, "lcr": "center", "val": "Πληρωτέο ποσό"},
            {"span": 1, "lcr": "right", "val": totals1[i]},
        ]
        if total != 0:
            if abs(total - gr2float(totals1[i])) > 0.05:
                raise ValueError
            adi["lines"].append(dline)

    return render(request, "koi/apodeijeis.html", adi)

koi/templates/koi/admin/base_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="el" class="h-full">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Διαχείριση Κοινοχρήστων{% endblock %}</title>
  <link rel="icon" href="{% static 'images/favicon.png' %}" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      darkMode: 'class',
      theme: {
        extend: {
          colors: {
            primary: {
              50: '#eff6ff',
              100: '#dbeafe',
              200: '#bfdbfe',
              300: '#93c5fd',
              400: '#60a5fa',
              500: '#3b82f6',
              600: '#2563eb',
              700: '#1d4ed8',
              800: '#1e40af',
              900: '#1e3a8a',
            }
          }
        }
      }
    }
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Inter', sans-serif;
    }
  </style>
</head>

<body class="h-full bg-gray-50 dark:bg-gray-900">
  <div class="min-h-full">
    <!-- Navigation -->
    <nav class="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 justify-between items-center">
          <!-- Logo -->
          <div class="flex-shrink-0">
            <a href="{% url 'koi:admin_dashboard' %}" class="text-xl font-bold text-primary-600 dark:text-primary-400">
              🏢 Κοινόχρηστα
            </a>
          </div>

          <!-- Desktop menu -->
          <div class="hidden lg:flex lg:items-center lg:space-x-4">
            <a href="{% url 'koi:admin_dashboard' %}"
              class="{% if request.resolver_match.url_name == 'admin_dashboard' %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Αρχική
            </a>
            <a href="{% url 'koi:admin_koinoxrista_list' %}"
              class="{% if 'koinoxrista' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Κοινόχρηστα
            </a>
            <a href="{% url 'koi:admin_dapanes_list' %}"
              class="{% if 'dapanes' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Δαπάνες
            </a>
            <a href="{% url 'koi:admin_diamerisma_list' %}"
              class="{% if 'diamerisma' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Διαμερίσματα
            </a>
            <a href="{% url 'koi:admin_category_list' %}"
              class="{% if 'category' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Κατηγορίες
            </a>
            <a href="{% url 'koi:admin_xiliosta_list' %}"
              class="{% if 'xiliosta' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Χιλιοστά
            </a>
            <a href="{% url 'koi:admin_diaxeiristis_list' %}"
              class="{% if 'diaxeiristis' in request.resolver_match.url_name %}bg-primary-50 text-primary-700 dark:bg-primary-900 dark:text-primary-200{% else %}text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-gray-700{% endif %} rounded-md px-3 py-2 text-sm font-medium">
              Διαχειριστές
            </a>
          </div>

          <!-- Desktop right side -->
          <div class="hidden lg:flex lg:items-center lg:space-x-4">
            <a href="{% url 'koi:index' %}"
              class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
            </a>
            <span class="text-sm text-gray-600 dark:text-gray-400">{{ user.username }}</span>
            <form method="post" action="{% url 'logout' %}" class="inline">
              {% csrf_token %}
              <button type="submit" class="text-sm text-red-600 hover:text-red-800 dark:text-red-400">Έξοδος</button>
            </form>
          </div>

          <!-- Mobile menu button -->
          <div class="lg:hidden">
            <button type="button" onclick="document.getElementById('mobile-menu').classList.toggle('hidden')"
              class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500"
              aria-controls="mobile-menu" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Mobile menu -->
      <div id="mobile-menu" class="hidden lg:hidden border-t border-gray-200 dark:border-gray-700">
        <div class="space-y-1 px-2 pb-3 pt-2">
          <a href="{% url 'koi:admin_dashboard' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Αρχική</a>
          <a href="{% url 'koi:admin_koinoxrista_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Κοινόχρηστα</a>
          <a href="{% url 'koi:admin_dapanes_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Δαπάνες</a>
          <a href="{% url 'koi:admin_diamerisma_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Διαμερίσματα</a>
          <a href="{% url 'koi:admin_category_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Κατηγορίες</a>
          <a href="{% url 'koi:admin_xiliosta_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Χιλιοστά</a>
          <a href="{% url 'koi:admin_diaxeiristis_list' %}"
            class="block rounded-md px-3 py-2 text-base font-medium text-gray-600 hover:bg-gray-50 hover:text-gray-900 dark:text-gray-300">Διαχειριστές</a>
        </div>
        <!-- Mobile user section -->
        <div class="border-t border-gray-200 dark:border-gray-700 px-4 py-3">
          <div class="flex items-center justify-between">
            <span class="text-sm text-gray-600 dark:text-gray-400">{{ user.username }}</span>
            <div class="flex items-center space-x-4">
              <a href="{% url 'koi:index' %}" class="text-gray-500 hover:text-gray-700 dark:text-gray-400">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                </svg>
              </a>
              <form method="post" action="{% url 'logout' %}" class="inline">
                {% csrf_token %}
                <button type="submit" class="text-sm text-red-600 hover:text-red-800 dark:text-red-400">Έξοδος</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- Messages -->
    {% if messages %}
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-4">
      {% for message in messages %}
      <div
        class="rounded-lg p-4 mb-2 {% if message.tags == 'success' %}bg-green-50 text-green-800 dark:bg-green-900 dark:text-green-200{% elif message.tags == 'error' %}bg-red-50 text-red-800 dark:bg-red-900 dark:text-red-200{% elif message.tags == 'warning' %}bg-yellow-50 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200{% else %}bg-blue-50 text-blue-800 dark:bg-blue-900 dark:text-blue-200{% endif %}">
        <div class="flex items-center">
          {% if message.tags == 'success' %}
          <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd"
              d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
              clip-rule="evenodd" />
          </svg>
          {% endif %}
          {{ message }}
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <!-- Main content -->
    <main class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      {% block content %}{% endblock %}
    </main>

    <!-- Footer -->
    <footer class="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 mt-auto">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
        <p class="text-center text-sm text-gray-500 dark:text-gray-400">
          © 2024 Διαχείριση Κοινοχρήστων. Όλα τα δικαιώματα διατηρούνται.
        </p>
      </div>
    </footer>
  </div>

  {% block extra_js %}{% endblock %}
</body>

</html>